### ndarray 정렬

In [1]:
import numpy as np

##### 1차원 배열 정렬

In [4]:
arr = np.random.randint(1,11,10)
arr

array([ 3,  6,  4, 10,  7,  6, 10,  1,  9,  7], dtype=int32)

In [7]:
print(np.sort(arr))
print(np.sort(arr)[::-1])

[ 1  3  4  6  6  7  7  9 10 10]
[10 10  9  7  7  6  6  4  3  1]


In [11]:
arr = np.random.randint(10, size=(3,4))
print(arr)

print('----행 방향 정렬(axis=0)----')
print(np.sort(arr, axis=0)) #  같은 열 안에서 정렬렬
print('----열 방향 정렬(axis=1)----')
print(np.sort(arr, axis=1)) # 같은 행 안에서 정렬
print('----정렬(axis=None)----')
print(np.sort(arr, axis=None)) # 축 무시(차원이 사라지고, 행/열 구분없이 모든 값이 정렬됨)

[[8 6 8 9]
 [2 6 9 2]
 [5 0 3 2]]
----행 방향 정렬(axis=0)----
[[2 0 3 2]
 [5 6 8 2]
 [8 6 9 9]]
----열 방향 정렬(axis=1)----
[[6 8 8 9]
 [2 2 6 9]
 [0 2 3 5]]
---- None 정렬 ----
[0 2 2 2 3 5 6 6 8 8 9 9]


##### np.argsort
- 배열의 값을 정렬했을 때, 각 값의 원래 인덱스를 반환
- 정렬할 때 어떤 순서로 값을 배치해야 하는지 알려주는 인덱스를 반환
- 배열의 값을 정렬한 후, 정렬된 순서에 해당하는 인덱스를 반환

In [13]:
arr = np.array([100,400,200,300])
print(np.sort(arr))
print(np.argsort(arr))

[100 200 300 400]
[0 2 3 1]


In [ ]:
names = np.array(['리사','로제','제니','지수'])
album_sales = np.array([900,870,1000,670])

# sales_desc = np.sort(album_sales)[::-1]

print(names[np.argsort(album_sales)[::-1]])

['제니' '리사' '로제' '지수']


In [ ]:
# 2차원 배열에서 argsort

arr = np.array([[2025,2,28],[17,18,30]])
print(np.argsort(arr))
print(np.argsort(arr, axis=1)) # 열 방향 정렬의 순서 (같은 행 안에서 정렬)
print(np.argsort(arr, axis=0)) # 행 방향 정렬의 순서 (같은 열 안에서 정렬)

[[1 2 0]
 [0 1 2]]
[[1 2 0]
 [0 1 2]]
[[1 0 0]
 [0 1 1]]
