### ndarray 병합 및 분할

In [3]:
import numpy as np

##### ndarray 요소 추가 및 삭제
- ndarray는 고정 길이 배열이므로 크기 변경이 불가하다 == 요소를 추가할 수 없다.

In [4]:
# np.insert(): 요소의 추가한 새로운 배열을 반환
arr = np.array([10,20,30])

arr1 =np.append(arr,40)
arr2 = np.insert(arr,1,15) # 새로운 변수 공간 선언
print(arr)

print(arr2 is arr, arr2) # insert는 요소를 추가하는데 추가한 것을 새롭게 반환해서 arr2에 저장했기 때문에 false를 반환함

[10 20 30]
False [10 15 20 30]


In [ ]:
# 2차원 배열에서 insert()
arr = np.arange(1,13).reshape(3,4)

print(np.insert(arr,1,100))

np.insert(arr,1,[100,200,300,400], axis=0) # 행 기준


[  1 100   2   3   4   5   6   7   8   9  10  11  12]


In [8]:
# delete
arr = np.arange(1,13).reshape(3,4)
print(np.delete(arr, 7)) # axis를 설정하지 않으면 1차원 배열로 변환 후 삭제제

[ 1  2  3  4  5  6  7  9 10 11 12]


# ndarray 병합
- np.append()
- np.vstack()
- np.hstack()
- np.concatenate()

In [4]:
arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(13,25).reshape(3,4)
arr1, arr2

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]))

In [ ]:
# append
print(np.append(arr1, arr2))
print(np.append(arr1, arr2, axis=0)) # 행 기준
print(np.append(arr1, arr2, axis=1)) # 열 기준

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


In [ ]:
# np.vstack: axis=0 병합 -> vertical
# 병합 대상상 ndarray를 튜플 혹은 리스트로 묶어서 전달해야 함함
np.vstack((arr1, arr2)) # 튜플로 묶기기

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
# np.hstack: axis=1 병합 -> horizontal
# 병합 대상상 ndarray를 튜플 혹은 리스트로 묶어서 전달해야 함함
np.hstack([arr1, arr2]) # 리스트로 묶기

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [ ]:
# np.concatenate()
# 병합 대상 ndarray를 튜플/리스트로 묶어서 전달해야 함
print(np.concatenate((arr1, arr2)))
print(np.concatenate((arr1, arr2, axis=0)))
print(np.concatenate((arr1, arr2, axis=1)))
print(np.concatenate((arr1, arr2, axis=None)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


### ndarray 분할
- np.split()

In [16]:
arr = np.concatenate((arr1, arr2))

print(np.split(arr, 2))
print(np.split(arr, 2, axis=0))
print(np.split(arr, 2, axis=1))

[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]
[array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]]), array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]


In [ ]:
# split을 사용할 때는 약수를 이용해서 사용해야 함
n = 3
print(np.split(arr, n, axis=0)) # 중간에 줘야 하는건 분할할 개수
print(np.split(arr, n, axis=1))

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]]), array([[17, 18, 19, 20],
       [21, 22, 23, 24]])]


ValueError: array split does not result in an equal division