# ndarray 형태변경

In [1]:
import numpy as np

In [ ]:
# reshape
# 요소의 갯수가 맞는 shape으로 변형이 가능
arr = np.arange(12)
print(arr.ndim, arr) # ndim: 깊이를 알아볼 수 있는 속성

arr = arr.reshape(3,4)
arr = arr.reshape(6,2)
arr = arr.reshape(1,12) # [[]] 이런 식으로 중첩이 되어 있음
# arr = arr.reshape(2,7)
print(arr.ndim, arr.shape)
print(arr)

# 다차원으로 reshape하기
print('\n--------------')
arr = arr.reshape(2,2,3)
# arr = arr.reshape(2,2,2)
print(arr.ndim, arr.shape)
print(arr)

1 [ 0  1  2  3  4  5  6  7  8  9 10 11]
2 (1, 12)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]

--------------
3 (2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [ ]:
# reshape() -> -1
arr = arr.reshape(-1) # 1차원으로 차원 줄이기
print(arr)

# -1인 축은 자동 계산
arr = arr.reshape(4,-1) # 행은 4행인데, 열이 -1 -> 요소의 갯수를 가지고 -1을 넣어준 축을 자동 계산 -> 즉, 행이나 열 하나만 지정하고 -1을 넣어도 reshape이 수행됨
print(arr)

arr = arr.reshape(-1,4)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [23]:
# np.ravel()
arr = np.arange(50).reshape(5, 10)
print(arr)
print(np.ravel(arr))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [ ]:
# np.expand_dims(): 차원 추가
arr_1d = np.arange(10)
print(arr_1d.shape, arr_1d)
print(np.expand_dims(arr_1d, axis=0))
print(np.expand_dims(arr_1d, axis=1))
print(np.expand_dims(arr_1d, axis=0).shape)
print(np.expand_dims(arr_1d, axis=1).shape)

(10,) [0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(1, 10)
(10, 1)


In [ ]:
arr_2d = np.array([[1,2],[3,4]])
print(arr_2d.shape, arr_2d)
print()
print(np.expand_dims(arr_2d, axis=0))
print(np.expand_dims(arr_2d, axis=1))
print(np.expand_dims(arr_2d, axis=0).shape) # 하나의 요소 안에 두 개의 요소가 있고, 그 안에 두 개의 요소가 있음
print(np.expand_dims(arr_2d, axis=1).shape) # 두개의 요소 안에 하나의 요소가 있고, 그 안에 두 개의 요소가 있음

print('----axis=2----')
print(np.expand_dims(arr_2d, axis=2))
print(np.expand_dims(arr_2d, axis=2).shape) # 두개의 요소 안에 두 개의 요소가 있고, 그 안에 하나의 요소가 있음

(2, 2) [[1 2]
 [3 4]]

[[[1 2]
  [3 4]]]
[[[1 2]]

 [[3 4]]]
(1, 2, 2)
(2, 1, 2)
----axis=2----
[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [34]:
# np.squeeze(): 차원의 값이 1일 때 제거
arr = np.array([[1,2]])
print(arr.shape)

arr2 = np.squeeze(arr)
arr2 = np.squeeze(arr, axis=0) # (2,2) -> (2,) : 0번째 인덱스를 삭제
print(arr2.shape)

(1, 2)
(2,)
