In [1]:
import numpy as np

# 실습1

다음과 같은 과일 판매량 데이터가 있습니다. 각 과일의 1분기와 2분기 판매량이 주어졌을 때, NumPy 배열을 사용하여 아래 문제를 해결하세요.

1. 1분기와 2분기의 과일별 총 판매량을 구하세요.
2. 과일별 평균 판매량을 구하세요.

- **데이터**:
    - 1분기 판매량: `[200, 340, 150, 400]` (사과, 배, 오렌지, 바나나)
    - 2분기 판매량: `[220, 300, 180, 420]` (사과, 배, 오렌지, 바나나)

In [10]:
arr1 = np.array([200,340,150,400])
arr2 = np.array([220,300,180,420])
total = np.add(arr1, arr2)
print(total)

print(np.sum(arr1))
print(np.sum(arr2))
print(np.sum(total))

print(np.average(arr1))
print(np.average(arr2))
print(np.average(total))

[420 640 330 820]
1090
1120
2210
272.5
280.0
552.5


# 실습2

다음 두 배열을 사용하여 각각의 요소별로 덧셈, 뺄셈, 곱셈, 나눗셈을 수행하세요.

In [4]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [5]:
print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1, arr2))

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


# 실습2: Dot Product
다음 두 배열 간의 내적 연산을 수행하세요.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# 실습3: 브로드캐스팅
아래의 2차원 배열과 1차원 배열을 브로드캐스팅하여 더하세요.

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])