# 다차원 첸서 (다차원 배열)

In [1]:
import numpy as np

### 다차원 배열의 계산 복습

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])

add_result = A + B

vec = np.array([1,2,3])
add_result2 = A + vec   # 브로드캐스팅: 두 개의 형태가 옹ㄴ전히 일치하지 않아도 알아서 요소를 확장해 각각의 요소에 대해 연산

print(add_result)
print(add_result2)

# dot_result = A.dot(B) # shape이 (2,3) (2,3)이라 내적이 안 됨 -> 첫째 행렬의 두번째, 둘째 행렬의 첫번째가 같아야함
dot_result = A.dot(B.T) # (2,3) (3,2) 
print(dot_result)

[[ 8 10 12]
 [14 16 18]]
[[2 4 6]
 [5 7 9]]
[[ 50  68]
 [122 167]]


---

### 다차원 배열의 계산으로 순전파 구현

In [11]:
# 입력 데이터
X = np.random.randn(4,5)    # 4개의 샘플, 5차원 feature (5개의 특성을 가지고 있는 4개의 샘플 데이터를 만든 것)


# 가중치
W = np.random.randn(5,3)    # 가중치 만들기 # 5개의 입력(feature), 3개의 뉴런으로 구성된 레이어

# 편향
b = np.random.randn(1,3)

# 선형 계산 (W*X + b)
z = np.dot(X, W) + b

# ReLU 활성화 함수
result = np.maximum(0,z)

print(result)

[[2.27775101 2.14601902 0.        ]
 [2.0902297  2.0445934  0.91707437]
 [2.51169579 1.66465087 0.        ]
 [0.         0.         0.        ]]
