# 출력층 설계 (Output layer)

In [1]:
!pip3 install torch torchvision torchaudio

   ---------------------------------------- 0.0/204.1 MB ? eta -:--:--
    --------------------------------------- 4.5/204.1 MB 26.9 MB/s eta 0:00:08
   - -------------------------------------- 9.2/204.1 MB 24.8 MB/s eta 0:00:08
   -- ------------------------------------- 13.1/204.1 MB 22.9 MB/s eta 0:00:09
   -- ------------------------------------- 15.2/204.1 MB 18.4 MB/s eta 0:00:11
   --- ------------------------------------ 16.3/204.1 MB 15.8 MB/s eta 0:00:12
   --- ------------------------------------ 17.3/204.1 MB 14.0 MB/s eta 0:00:14
   --- ------------------------------------ 19.1/204.1 MB 13.0 MB/s eta 0:00:15
   ---- ----------------------------------- 21.5/204.1 MB 12.7 MB/s eta 0:00:15
   ---- ----------------------------------- 22.5/204.1 MB 11.9 MB/s eta 0:00:16
   ---- ----------------------------------- 24.1/204.1 MB 11.4 MB/s eta 0:00:16
   ----- ---------------------------------- 26.7/204.1 MB 11.5 MB/s eta 0:00:16
   ----- ---------------------------------- 30.1/20

In [4]:
import warnings
warnings.filterwarnings('ignore')

### 소프트맥스 오버플로우 방지

In [5]:
import numpy as np

def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

def stable_softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)


x = np.array([1000, 1001, 1002])

print(softmax(x))
print(stable_softmax(x))

[nan nan nan]
[0.09003057 0.24472847 0.66524096]


- PyTorch 라이브러리 함수 사용

In [6]:
import torch
import torch.nn.functional as F

x = torch.tensor([1000, 1001, 1002], dtype=torch.float32)

softmax_output = F.softmax(x, dim=0)    # dim: softmax를 적용할 축
print(softmax_output)

sigmoid_output = torch.sigmoid(x)
print(sigmoid_output)

tensor([0.0900, 0.2447, 0.6652])
tensor([1., 1., 1.])


### 손실 함수와 연계

In [7]:
import torch
import torch.nn as nn
import torch.optim as optim

# 간단한 다중 클래스 분류 모델 정의 (입력 값: 5개, 출력: 3 클래스)
class SimpleMultiClassModel(nn.Module):
    def __init__(self):
        super(SimpleMultiClassModel, self).__init__()
        self.fc = nn.Linear(5, 3)

    def forward(self, x):
        return self.fc(x)
    
model = SimpleMultiClassModel()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# 데이터 생성
inputs = torch.randn(4, 5)
labels = torch.tensor([0, 2, 1, 0])

for _ in range(10):
    preds = model(inputs)           # 순전파
    loss = criterion(preds, labels) # 손실 계산
    print(loss.item())

    optimizer.zero_grad()   # 이전 단계에서 계산된 기울기를 0으로 초기화
    loss.backward()         # 손실에 대한 역전파 수행 (파라미터에 대한 기울기 계산)
    optimizer.step()        # 계산된 기울기를 사용하여 옵티마이저가 모델의 파라미터 업데이트

1.1914362907409668
1.158203125
1.1259335279464722
1.094651699066162
1.0643792152404785
1.035133719444275
1.0069290399551392
0.979773998260498
0.9536721706390381
0.9286216497421265
